# Generated by Django 5.2.4 on 2025-07-07 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visuospatial", models.FloatField(default=0)),
                ("naming", models.FloatField(default=0)),
                ("memory", models.FloatField(default=0)),
                ("attention", models.FloatField(default=0)),
                ("language", models.FloatField(default=0)),
                ("abstraction", models.FloatField(default=0)),
                ("delayed_recall", models.FloatField(default=0)),
                ("orientation", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
